name: Deploy to Server

on:
  push:
    branches:
      - main  # Деплой при пуше в main ветку

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd /home/django/Document_bot
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart telegram-bot
          echo "Deployment completed successfully!"
